[package]
name = "tiny-secp256k1-wasm"
version = "0.1.0"
authors = ["junderw <junderwood@bitcoinbank.co.jp>", "yuki-js <20838151+yuki-js@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/junderw/tiny-secp256k1-wasm"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
console_error_panic_hook = { version = "0.1.1", optional = true }
wee_alloc = { version = "0.4.2", optional = true }
secp256k1 = { git = "https://github.com/rust-bitcoin/rust-secp256k1", features = ["rand"] }
rand = { version = "0.6", features = ["wasm-bindgen"] }
js-sys = "0.3.40"

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
opt-level = "s"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
