[package]
name = "secp256k1"
version = "0.0.0"
authors = []
edition = "2018"
description = "A Rust library for building tiny-secp256k1 Node.js bindings / WASM"
license = "MIT"
publish = false

[dependencies]
rand = "0.8.3"
secp256k1-sys = "0.4.0"
